<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170809172051 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_accounttoken (persistence_object_identifier VARCHAR(40) NOT NULL, user BIGINT DEFAULT NULL, token VARCHAR(255) NOT NULL, type SET(\'registration\', \'password_reset\', \'password_change\'), expiredate DATETIME NOT NULL, INDEX IDX_B71BBD138D93D649 (user), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_activity (uid BIGINT AUTO_INCREMENT NOT NULL, user BIGINT DEFAULT NULL, date DATETIME NOT NULL, eventtype ENUM(\'create_register\', \'update_register\', \'delete_register\', \'create_card\', \'update_card\', \'delete_card\'), ref LONGTEXT DEFAULT NULL, INDEX IDX_4E7DDA398D93D649 (user), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_card (uid BIGINT AUTO_INCREMENT NOT NULL, author BIGINT DEFAULT NULL, register BIGINT DEFAULT NULL, crdate DATETIME NOT NULL, tags LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:simple_array)\', question LONGTEXT NOT NULL, type ENUM(\'single-choice\', \'multiple-choice\', \'text-input\', \'self-validate\'), content LONGTEXT NOT NULL COMMENT \'(DC2Type:object)\', INDEX IDX_3382D44FBDAFD8C8 (author), INDEX IDX_3382D44F5FF94014 (register), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_cardstatistic (uid BIGINT AUTO_INCREMENT NOT NULL, user BIGINT DEFAULT NULL, card BIGINT DEFAULT NULL, value VARCHAR(255) NOT NULL, date DATETIME NOT NULL, INDEX IDX_7A807C748D93D649 (user), INDEX IDX_7A807C74161498D3 (card), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_member (uid BIGINT AUTO_INCREMENT NOT NULL, user BIGINT DEFAULT NULL, register BIGINT DEFAULT NULL, role SET(\'owner\', \'editor\', \'subscriber\'), INDEX IDX_D27A17438D93D649 (user), INDEX IDX_D27A17435FF94014 (register), UNIQUE INDEX UNIQ_D27A17438D93D6495FF94014 (user, register), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_register (uid BIGINT AUTO_INCREMENT NOT NULL, crdate DATETIME NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE gocardteam_gocardapi_domain_model_v1_user (uid BIGINT AUTO_INCREMENT NOT NULL, account VARCHAR(40) DEFAULT NULL, displayname VARCHAR(60) NOT NULL, email VARCHAR(255) NOT NULL, status ENUM(\'new\', \'verified\', \'active\'), UNIQUE INDEX UNIQ_A8059AD57D3656A4 (account), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_accounttoken ADD CONSTRAINT FK_B71BBD138D93D649 FOREIGN KEY (user) REFERENCES gocardteam_gocardapi_domain_model_v1_user (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_activity ADD CONSTRAINT FK_4E7DDA398D93D649 FOREIGN KEY (user) REFERENCES gocardteam_gocardapi_domain_model_v1_user (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_card ADD CONSTRAINT FK_3382D44FBDAFD8C8 FOREIGN KEY (author) REFERENCES gocardteam_gocardapi_domain_model_v1_user (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_card ADD CONSTRAINT FK_3382D44F5FF94014 FOREIGN KEY (register) REFERENCES gocardteam_gocardapi_domain_model_v1_register (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_cardstatistic ADD CONSTRAINT FK_7A807C748D93D649 FOREIGN KEY (user) REFERENCES gocardteam_gocardapi_domain_model_v1_user (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_cardstatistic ADD CONSTRAINT FK_7A807C74161498D3 FOREIGN KEY (card) REFERENCES gocardteam_gocardapi_domain_model_v1_card (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_member ADD CONSTRAINT FK_D27A17438D93D649 FOREIGN KEY (user) REFERENCES gocardteam_gocardapi_domain_model_v1_user (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_member ADD CONSTRAINT FK_D27A17435FF94014 FOREIGN KEY (register) REFERENCES gocardteam_gocardapi_domain_model_v1_register (uid)');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_user ADD CONSTRAINT FK_A8059AD57D3656A4 FOREIGN KEY (account) REFERENCES neos_flow_security_account (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_cardstatistic DROP FOREIGN KEY FK_7A807C74161498D3');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_card DROP FOREIGN KEY FK_3382D44F5FF94014');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_member DROP FOREIGN KEY FK_D27A17435FF94014');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_accounttoken DROP FOREIGN KEY FK_B71BBD138D93D649');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_activity DROP FOREIGN KEY FK_4E7DDA398D93D649');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_card DROP FOREIGN KEY FK_3382D44FBDAFD8C8');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_cardstatistic DROP FOREIGN KEY FK_7A807C748D93D649');
        $this->addSql('ALTER TABLE gocardteam_gocardapi_domain_model_v1_member DROP FOREIGN KEY FK_D27A17438D93D649');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_accounttoken');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_activity');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_card');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_cardstatistic');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_member');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_register');
        $this->addSql('DROP TABLE gocardteam_gocardapi_domain_model_v1_user');
    }
}