/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GoCardApi);
  }
}(this, function(expect, GoCardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GoCardApi.CardsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardsApi', function() {
    describe('cardsCardIdDelete', function() {
      it('should call cardsCardIdDelete successfully', function(done) {
        //uncomment below and update the code to test cardsCardIdDelete
        //instance.cardsCardIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsCardIdPost', function() {
      it('should call cardsCardIdPost successfully', function(done) {
        //uncomment below and update the code to test cardsCardIdPost
        //instance.cardsCardIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cardsPut', function() {
      it('should call cardsPut successfully', function(done) {
        //uncomment below and update the code to test cardsPut
        //instance.cardsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCard', function() {
      it('should call getCard successfully', function(done) {
        //uncomment below and update the code to test getCard
        //instance.getCard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsOfRegister', function() {
      it('should call getCardsOfRegister successfully', function(done) {
        //uncomment below and update the code to test getCardsOfRegister
        //instance.getCardsOfRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registersRegisterIdCardsPost', function() {
      it('should call registersRegisterIdCardsPost successfully', function(done) {
        //uncomment below and update the code to test registersRegisterIdCardsPost
        //instance.registersRegisterIdCardsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
