/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GoCardApi);
  }
}(this, function(expect, GoCardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GoCardApi.CardsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CardsApi', function() {
    describe('addCardsToRegister', function() {
      it('should call addCardsToRegister successfully', function(done) {
        //uncomment below and update the code to test addCardsToRegister
        //instance.addCardsToRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteCard', function() {
      it('should call deleteCard successfully', function(done) {
        //uncomment below and update the code to test deleteCard
        //instance.deleteCard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findByCardsByRegister', function() {
      it('should call findByCardsByRegister successfully', function(done) {
        //uncomment below and update the code to test findByCardsByRegister
        //instance.findByCardsByRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCard', function() {
      it('should call getCard successfully', function(done) {
        //uncomment below and update the code to test getCard
        //instance.getCard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCard', function() {
      it('should call updateCard successfully', function(done) {
        //uncomment below and update the code to test updateCard
        //instance.updateCard(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateCards', function() {
      it('should call updateCards successfully', function(done) {
        //uncomment below and update the code to test updateCards
        //instance.updateCards(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
