/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GoCardApi);
  }
}(this, function(expect, GoCardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GoCardApi.MembersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MembersApi', function() {
    describe('getMembersOfRegister', function() {
      it('should call getMembersOfRegister successfully', function(done) {
        //uncomment below and update the code to test getMembersOfRegister
        //instance.getMembersOfRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registersRegisterIdMembersMemberIdDelete', function() {
      it('should call registersRegisterIdMembersMemberIdDelete successfully', function(done) {
        //uncomment below and update the code to test registersRegisterIdMembersMemberIdDelete
        //instance.registersRegisterIdMembersMemberIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registersRegisterIdMembersMemberIdPost', function() {
      it('should call registersRegisterIdMembersMemberIdPost successfully', function(done) {
        //uncomment below and update the code to test registersRegisterIdMembersMemberIdPost
        //instance.registersRegisterIdMembersMemberIdPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registersRegisterIdMembersPost', function() {
      it('should call registersRegisterIdMembersPost successfully', function(done) {
        //uncomment below and update the code to test registersRegisterIdMembersPost
        //instance.registersRegisterIdMembersPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registersRegisterIdMembersPut', function() {
      it('should call registersRegisterIdMembersPut successfully', function(done) {
        //uncomment below and update the code to test registersRegisterIdMembersPut
        //instance.registersRegisterIdMembersPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
