/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GoCardApi);
  }
}(this, function(expect, GoCardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GoCardApi.RegistersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RegistersApi', function() {
    describe('addCardsToRegister', function() {
      it('should call addCardsToRegister successfully', function(done) {
        //uncomment below and update the code to test addCardsToRegister
        //instance.addCardsToRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addMembersToRegister', function() {
      it('should call addMembersToRegister successfully', function(done) {
        //uncomment below and update the code to test addMembersToRegister
        //instance.addMembersToRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addRegister', function() {
      it('should call addRegister successfully', function(done) {
        //uncomment below and update the code to test addRegister
        //instance.addRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMemberOfRegister', function() {
      it('should call deleteMemberOfRegister successfully', function(done) {
        //uncomment below and update the code to test deleteMemberOfRegister
        //instance.deleteMemberOfRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRegister', function() {
      it('should call deleteRegister successfully', function(done) {
        //uncomment below and update the code to test deleteRegister
        //instance.deleteRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findAllRegisters', function() {
      it('should call findAllRegisters successfully', function(done) {
        //uncomment below and update the code to test findAllRegisters
        //instance.findAllRegisters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findByCardsByRegister', function() {
      it('should call findByCardsByRegister successfully', function(done) {
        //uncomment below and update the code to test findByCardsByRegister
        //instance.findByCardsByRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findByRegisterById', function() {
      it('should call findByRegisterById successfully', function(done) {
        //uncomment below and update the code to test findByRegisterById
        //instance.findByRegisterById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findMembersByRegister', function() {
      it('should call findMembersByRegister successfully', function(done) {
        //uncomment below and update the code to test findMembersByRegister
        //instance.findMembersByRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMemberByRegister', function() {
      it('should call getMemberByRegister successfully', function(done) {
        //uncomment below and update the code to test getMemberByRegister
        //instance.getMemberByRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMembersOfRegister', function() {
      it('should call updateMembersOfRegister successfully', function(done) {
        //uncomment below and update the code to test updateMembersOfRegister
        //instance.updateMembersOfRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRegister', function() {
      it('should call updateRegister successfully', function(done) {
        //uncomment below and update the code to test updateRegister
        //instance.updateRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
