/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GoCardApi);
  }
}(this, function(expect, GoCardApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GoCardApi.RegistersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RegistersApi', function() {
    describe('addRegister', function() {
      it('should call addRegister successfully', function(done) {
        //uncomment below and update the code to test addRegister
        //instance.addRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteRegister', function() {
      it('should call deleteRegister successfully', function(done) {
        //uncomment below and update the code to test deleteRegister
        //instance.deleteRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCardsOfRegister', function() {
      it('should call getCardsOfRegister successfully', function(done) {
        //uncomment below and update the code to test getCardsOfRegister
        //instance.getCardsOfRegister(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRegisterById', function() {
      it('should call getRegisterById successfully', function(done) {
        //uncomment below and update the code to test getRegisterById
        //instance.getRegisterById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registersRegisterIdCardsPost', function() {
      it('should call registersRegisterIdCardsPost successfully', function(done) {
        //uncomment below and update the code to test registersRegisterIdCardsPost
        //instance.registersRegisterIdCardsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateRegisterWithForm', function() {
      it('should call updateRegisterWithForm successfully', function(done) {
        //uncomment below and update the code to test updateRegisterWithForm
        //instance.updateRegisterWithForm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
