# GitLab Continuous Integration

stages:
  - lint
  - test
  - build
  - dockerBuild

variables:
  GIT_STRATEGY: clone
  DOCKER_DRIVER: overlay

build:client:
  image: node
  stage: build
  tags:
    - docker
  only:
#    - master
  before_script:
    - yarn install
  script:
    - yarn run build

build:flow:
  image: composer
  stage: build
  tags:
    - docker
  only:
#    - master
  before_script:
    - composer install
  script:
    - echo "Nothing to actually build"

build_docker:
  image: docker:latest
  stage: dockerBuild
  tags:
    - docker
  only:
#    - master
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl
    - curl -L https://github.com/docker/compose/releases/download/$dockerComposeVersion/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
  script:
    - docker-compose -f .docker-compose.production.yml build