# GitLab Continuous Integration

stages:
  - lint
  - test
  - build
  - bundle
  - docker

variables:
  GIT_STRATEGY: clone
  DOCKER_DRIVER: overlay
  DOCKER_COMPOSE_VERSION: 1.15.0
  API_HOST: gocard.jdoubleu.de
  API_SCHEMA: https
  DOCKER_DRIVER: overlay

build:client:
  image: node
  stage: build
  tags:
    - docker
  only:
    - master
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - node_modules/
  before_script:
    - yarn install
    - |
        sed -i "s/host:.*/host: \"${API_HOST}\"/" api_schema.yaml
    - |
        sed -i "s/  - \"http\"*/  - \"${API_SCHEMA}\"/" api_schema.yaml
  script:
    - yarn run api-gen
    - CI= yarn run build
    - |
        sed 's/>/>\n/g' Packages/Application/GoCardTeam.GoCardApi/Resources/Public/index.html | sed -r "s/_Resources\/Static\/Packages\/(.+\.[^\/\\\"]+)\/(.+?)\\\"(.+\".+\")/\{f\:uri\.resource(path\: '\2'\)}\\\"\3/" > Packages/Application/GoCardTeam.GoCardApi/Resources/Private/Templates/Standard/Index.html
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    expire_in: 1 day
    paths:
      - Packages/Application/GoCardTeam.GoCardApi/Resources/Public/
      - Packages/Application/GoCardTeam.GoCardApi/Resources/Private/Templates/Standard/Index.html

build:flow:
  image: composer
  stage: build
  tags:
    - docker
  only:
    - master
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - /composer/cache/
  before_script:
    - composer install
  script:
    - echo "Nothing to actually build"
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    expire_in: 1 day
    paths:
      - Configuration/
      - Packages/
      - Web/
      - flow

build:bundle:
  image: alpine
  stage: bundle
  tags:
    - docker
  only:
    - master
  dependencies:
    - build:client
    - build:flow
  script:
    - echo Bundling client and server
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    expire_in: 1 day
    paths:
      - Configuration/
      - Packages/
      - Web/
      - flow
      - docker-compose.production.yml

build:docker:
  image: docker:latest
  stage: docker
  tags:
    - docker
  only:
    - master
  services:
    - docker:dind
  before_script:
    - apk add --no-cache python python-dev py-pip build-base
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose.production.yml build
    - mkdir -p images/
    - for img in $(docker images | grep ${PWD##*/} | awk '{ print $1 }'); do docker save $img -o images/image_$img; done;
  artifacts:
    name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
    expire_in: 1 day
    paths:
      - images/*
      - docker-compose.production.yml
