#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

Neos:
  Flow:
    persistence:
      backendOptions:
        dbname: '%env:DATABASE_NAME%'       # adjust to your database name
        user: '%env:DATABASE_USER%'             # adjust to your database user
        password: '%env:DATABASE_PASSWORD%'         # adjust to your database password
        port: '%env:DATABASE_PORT%'         # adjust to your database password

    http:
      baseUri: '%env:BASE_URI%'

  SwiftMailer:
    transport:
      type: 'Swift_SmtpTransport'
      options:
        options:
        host: '%env:SMTP_HOST%'
        port: '%env:SMTP_PORT%'
        username: '%env:SMTP_USER%'
        password: '%env:SMTP_PASSWORD%'
        localDomain: '%env:SMTP_DOMAIN%'

GoCardTeam:
  GoCardApi:
    security:
      accessToken:
        # 1 hour lifetime
        lifetime: 3600

    mail:
      from:
        name: 'GoCard'
        address: '%env:SMTP_ADDRESS%'