/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Card', 'model/Member', 'model/MultipleValidationResponse', 'model/Register', 'model/ValidationResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Card'), require('../model/Member'), require('../model/MultipleValidationResponse'), require('../model/Register'), require('../model/ValidationResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.GoCardApi) {
      root.GoCardApi = {};
    }
    root.GoCardApi.RegistersApi = factory(root.GoCardApi.ApiClient, root.GoCardApi.Card, root.GoCardApi.Member, root.GoCardApi.MultipleValidationResponse, root.GoCardApi.Register, root.GoCardApi.ValidationResponse);
  }
}(this, function(ApiClient, Card, Member, MultipleValidationResponse, Register, ValidationResponse) {
  'use strict';

  /**
   * Registers service.
   * @module api/RegistersApi
   * @version 1.0.0
   */

  /**
   * Constructs a new RegistersApi. 
   * @alias module:api/RegistersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addRegister operation.
     * @callback module:api/RegistersApi~addRegisterCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Register} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add a new register
     * 
     * @param {module:model/Register} body Register object that needs to be added
     * @param {module:api/RegistersApi~addRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Register}
     */
    this.addRegister = function(body, callback) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body == undefined || body == null) {
        throw new Error("Missing the required parameter 'body' when calling addRegister");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Register;

      return this.apiClient.callApi(
        '/registers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteRegister operation.
     * @callback module:api/RegistersApi~deleteRegisterCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a register
     * 
     * @param {Number} registerId ID of register that should be deleted
     * @param {module:api/RegistersApi~deleteRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteRegister = function(registerId, callback) {
      var postBody = null;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling deleteRegister");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/registers/{registerId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getCardsOfRegister operation.
     * @callback module:api/RegistersApi~getCardsOfRegisterCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Card>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all cards of this register
     * Returns all cards of the given register
     * @param {Number} registerId ID of register which cards to get
     * @param {module:api/RegistersApi~getCardsOfRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Card>}
     */
    this.getCardsOfRegister = function(registerId, callback) {
      var postBody = null;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling getCardsOfRegister");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Card];

      return this.apiClient.callApi(
        '/registers/{registerId}/cards/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getMembersOfRegister operation.
     * @callback module:api/RegistersApi~getMembersOfRegisterCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Member>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all members of this register
     * Returns all members of the given register
     * @param {Number} registerId ID of the register
     * @param {module:api/RegistersApi~getMembersOfRegisterCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Member>}
     */
    this.getMembersOfRegister = function(registerId, callback) {
      var postBody = null;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling getMembersOfRegister");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Member];

      return this.apiClient.callApi(
        '/registers/{registerId}/members/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getRegisterById operation.
     * @callback module:api/RegistersApi~getRegisterByIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Register} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Find register by ID
     * Returns a single register
     * @param {Number} registerId ID of register to get
     * @param {module:api/RegistersApi~getRegisterByIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Register}
     */
    this.getRegisterById = function(registerId, callback) {
      var postBody = null;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling getRegisterById");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = Register;

      return this.apiClient.callApi(
        '/registers/{registerId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the registersRegisterIdCardsPost operation.
     * @callback module:api/RegistersApi~registersRegisterIdCardsPostCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Card>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create multiple new cards
     * Creates multiple new cards and adds them to a register
     * @param {Number} registerId ID register the cards should be added to
     * @param {Array.<module:model/Card>} cards Cards to be created
     * @param {module:api/RegistersApi~registersRegisterIdCardsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Card>}
     */
    this.registersRegisterIdCardsPost = function(registerId, cards, callback) {
      var postBody = cards;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling registersRegisterIdCardsPost");
      }

      // verify the required parameter 'cards' is set
      if (cards == undefined || cards == null) {
        throw new Error("Missing the required parameter 'cards' when calling registersRegisterIdCardsPost");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [Card];

      return this.apiClient.callApi(
        '/registers/{registerId}/cards/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the registersRegisterIdMembersMemberIdDelete operation.
     * @callback module:api/RegistersApi~registersRegisterIdMembersMemberIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Remove a member from this register
     * Removes a member from a register
     * @param {Number} registerId ID of the register
     * @param {Number} memberId ID of the member which should be removed
     * @param {module:api/RegistersApi~registersRegisterIdMembersMemberIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.registersRegisterIdMembersMemberIdDelete = function(registerId, memberId, callback) {
      var postBody = null;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling registersRegisterIdMembersMemberIdDelete");
      }

      // verify the required parameter 'memberId' is set
      if (memberId == undefined || memberId == null) {
        throw new Error("Missing the required parameter 'memberId' when calling registersRegisterIdMembersMemberIdDelete");
      }


      var pathParams = {
        'registerId': registerId,
        'memberId': memberId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/registers/{registerId}/members/{memberId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the registersRegisterIdMembersMemberIdPost operation.
     * @callback module:api/RegistersApi~registersRegisterIdMembersMemberIdPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update member of a register
     * Updates a specific member of a register
     * @param {Number} registerId ID of the register
     * @param {module:model/Member} member Member to be updated
     * @param {module:api/RegistersApi~registersRegisterIdMembersMemberIdPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.registersRegisterIdMembersMemberIdPost = function(registerId, member, callback) {
      var postBody = member;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling registersRegisterIdMembersMemberIdPost");
      }

      // verify the required parameter 'member' is set
      if (member == undefined || member == null) {
        throw new Error("Missing the required parameter 'member' when calling registersRegisterIdMembersMemberIdPost");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/registers/{registerId}/members/{memberId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the registersRegisterIdMembersPost operation.
     * @callback module:api/RegistersApi~registersRegisterIdMembersPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add member to this register
     * Adds a new member to this register
     * @param {Number} registerId ID of the register
     * @param {module:model/Member} member Member to be added
     * @param {module:api/RegistersApi~registersRegisterIdMembersPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.registersRegisterIdMembersPost = function(registerId, member, callback) {
      var postBody = member;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling registersRegisterIdMembersPost");
      }

      // verify the required parameter 'member' is set
      if (member == undefined || member == null) {
        throw new Error("Missing the required parameter 'member' when calling registersRegisterIdMembersPost");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/registers/{registerId}/members/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the registersRegisterIdMembersPut operation.
     * @callback module:api/RegistersApi~registersRegisterIdMembersPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update members of this register
     * Updates all members with their permission of this register
     * @param {Number} registerId ID of the register
     * @param {Array.<module:model/Member>} members Members to be updated
     * @param {module:api/RegistersApi~registersRegisterIdMembersPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.registersRegisterIdMembersPut = function(registerId, members, callback) {
      var postBody = members;

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling registersRegisterIdMembersPut");
      }

      // verify the required parameter 'members' is set
      if (members == undefined || members == null) {
        throw new Error("Missing the required parameter 'members' when calling registersRegisterIdMembersPut");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/registers/{registerId}/members/', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the updateRegisterWithForm operation.
     * @callback module:api/RegistersApi~updateRegisterWithFormCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a register by ID
     * 
     * @param {Number} registerId ID of register that needs to be updated
     * @param {Object} opts Optional parameters
     * @param {module:model/Register} opts.name Updated name of the pet
     * @param {module:api/RegistersApi~updateRegisterWithFormCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.updateRegisterWithForm = function(registerId, opts, callback) {
      opts = opts || {};
      var postBody = opts['name'];

      // verify the required parameter 'registerId' is set
      if (registerId == undefined || registerId == null) {
        throw new Error("Missing the required parameter 'registerId' when calling updateRegisterWithForm");
      }


      var pathParams = {
        'registerId': registerId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['api_key'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/registers/{registerId}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
