/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MultipleValidationResponseItems'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MultipleValidationResponseItems'));
  } else {
    // Browser globals (root is window)
    if (!root.GoCardApi) {
      root.GoCardApi = {};
    }
    root.GoCardApi.MultipleValidationResponse = factory(root.GoCardApi.ApiClient, root.GoCardApi.MultipleValidationResponseItems);
  }
}(this, function(ApiClient, MultipleValidationResponseItems) {
  'use strict';




  /**
   * The MultipleValidationResponse model module.
   * @module model/MultipleValidationResponse
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>MultipleValidationResponse</code>.
   * Same as ValidationResponse but for multiple elements
   * @alias module:model/MultipleValidationResponse
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>MultipleValidationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MultipleValidationResponse} obj Optional instance to populate.
   * @return {module:model/MultipleValidationResponse} The populated <code>MultipleValidationResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [MultipleValidationResponseItems]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/MultipleValidationResponseItems>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


