Neos:
  Flow:
    mvc:
      routes:
        'GoCardTeam.GoCardApi':
          position: 'start'

    security:
      authentication:
        providers:
          'LocalAuthenticationProvider':
            provider: 'GoCardTeam\GoCardApi\Security\Authentication\Provider\v1\PersistedEmailPasswordProvider'
            requestPatterns:
              'GoCardTeam.GoCardApi:ApiAccessRequest':
                pattern: 'ControllerObjectName'
                patternOptions:
                  'controllerObjectNamePattern': 'GoCardTeam\GoCardApi\Controller\v1\LocalAccountAuthenticationController'
          'AccessTokenAuthenticationProvider':
            provider: 'GoCardTeam\GoCardApi\Security\Authentication\Provider\v1\AccessTokenProvider'
            providerOptions:
              localAccountProviderName: 'LocalAuthenticationProvider'
            requestPatterns:
              'GoCardTeam.GoCardApi:ApiAccess':
                pattern: 'ControllerObjectName'
                patternOptions:
                  'controllerObjectNamePattern': 'GoCardTeam\GoCardApi\Controller\v1\Endpoint\.*'
