Neos:
  Flow:
    mvc:
      routes:
        'GoCardTeam.GoCard':
          position: 'start'

    security:
      authentication:
        providers:
          'LocalAuthenticationProvider':
            provider: 'PersistedUsernamePasswordProvider'
            token: '\GoCardTeam\GoCard\Security\Authentication\Token\Api\v1\EmailPassword'
            requestPatterns:
              'GoCardTeam.GoCard:ApiAccessRequest':
                pattern: 'ControllerObjectName'
                patternOptions:
                  'controllerObjectNamePattern': '\GoCardTeam\GoCard\Controller\Api\v1\LocalAccountAuthenticationController'
          'AccessTokenAuthenticationProvider':
            provider: '\GoCardTeam\GoCard\Security\Authentication\Provider\Api\v1\AccessTokenProvider'
            providerOptions:
              localAccountProviderName: 'PersistedUsernamePasswordProvider'
            requestPatterns:
              'GoCardTeam.GoCard:ApiAccess':
                pattern: 'ControllerObjectName'
                patternOptions:
                  'controllerObjectNamePattern': '\GoCardTeam\GoCard\Controller\Api\v1\Endpoint\.*'
