Neos:
  Flow:
    security:
      authentication:
        providers:
          'LocalAuthenticationProvider':
            provider: 'PersistedUsernamePasswordProvider'
            token: '\GoCardTeam\GoCard\Security\Authentication\Token\Api\v1\EmailPassword
          'AccessTokenAuthenticationProvider':
            provider: '\GoCardTeam\GoCard\Security\Authentication\Provider\Api\v1\AccessTokenProvider'
            providerOptions:
              localAccountProviderName: 'PersistedUsernamePasswordProvider'