Neos:
  Flow:
    security:
      authentication:
        providers:
          'LocalAuthenticationProvider':
            provider: 'PersistedUsernamePasswordProvider'
            token: '\GoCardTeam\GoCard\Security\Authentication\Token\Api\v1\EmailPassword