/**
 * GoCard API
 * GoCard API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.GoCardApi) {
      root.GoCardApi = {};
    }
    root.GoCardApi.Member = factory(root.GoCardApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Member model module.
   * @module model/Member
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Member</code>.
   * @alias module:model/Member
   * @class
   * @param userid {Number} ID of the user
   * @param scope {Array.<module:model/Member.ScopeEnum>} 
   */
  var exports = function(userid, scope) {
    var _this = this;

    _this['userid'] = userid;
    _this['scope'] = scope;
  };

  /**
   * Constructs a <code>Member</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Member} obj Optional instance to populate.
   * @return {module:model/Member} The populated <code>Member</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userid')) {
        obj['userid'] = ApiClient.convertToType(data['userid'], 'Number');
      }
      if (data.hasOwnProperty('scope')) {
        obj['scope'] = ApiClient.convertToType(data['scope'], ['String']);
      }
    }
    return obj;
  }

  /**
   * ID of the user
   * @member {Number} userid
   */
  exports.prototype['userid'] = undefined;
  /**
   * @member {Array.<module:model/Member.ScopeEnum>} scope
   */
  exports.prototype['scope'] = undefined;


  /**
   * Allowed values for the <code>scope</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ScopeEnum = {
    /**
     * value: "read"
     * @const
     */
    "read": "read",
    /**
     * value: "write"
     * @const
     */
    "write": "write",
    /**
     * value: "update"
     * @const
     */
    "update": "update"  };


  return exports;
}));


