#                                                                        #
# Example Settings                                                       #
#                                                                        #
# This file contains settings for various parts of the application.      #
# Copy this file to Settings.yaml, and adjust as necessary.              #
#                                                                        #
# Please refer to the default settings file(s) or the manuals for        #
# possible configuration options.                                        #
#                                                                        #

Neos:
  Flow:
    persistence:
      backendOptions:
        host: 'mysql'
        dbname: 'flow'       # adjust to your database name
        user: 'root'             # adjust to your database user
        password: 'jFaa6D4JJPB3sNY8RRwjUF5e'         # adjust to your database password
        port: '3306'

       # if you want to log executed SQL queries, enable the next 2 lines
#      doctrine:
#        sqlLogger: 'Neos\Flow\Persistence\Doctrine\Logging\SqlLogger'

  SwiftMailer:
    transport:
      type: 'Neos\SwiftMailer\Transport\MboxTransport'
      options:
        mboxPathAndFilename: '%FLOW_PATH_DATA%/Temporary/Development/SwiftMailer/sent-mail'

GoCardTeam:
  GoCardApi:
    security:
      accessToken:
        # 1 year lifetime
        lifetime: 31536000

    mail:
      from:
        name: 'GoCard'
        address: 'gocard@localhost'